=== lpenaud/metaprog-m2/tests/carnet.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT carnet (type, contact*)>
<!ELEMENT type (#PCDATA)>
<!ELEMENT contact (nom, prenom, telephone, information*)>
<!ELEMENT nom (#PCDATA)>
<!ELEMENT prenom (#PCDATA)>
<!ELEMENT telephone (#PCDATA)>
<!ELEMENT information (libelle, texte)>
<!ELEMENT libelle (#PCDATA)>
<!ELEMENT texte (#PCDATA)>

=== lpenaud/metaprog-m2/def/carnet/testCarnet3.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE carnet PUBLIC "CarnetId" "carnet.dtd">
<carnet>
	<type>commun</type>
	<contact>
		<nom>Bessac</nom>
		<prenom>Bilbo</prenom>
		<telephone>0298989898</telephone>
		<information>
			<football>Loisir</football>
		</information>
	</contact>
</carnet>

=== lpenaud/metaprog-m2/tests/test2.xml
<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE Carnet PUBLIC "CarnetId" "Carnet.dtd"><carnet><type>commun</type><contact><nom>Bessac</nom><prenom>Bilbo</prenom><information><libelle>Hobby</libelle><texte>Musique</texte><information><libelle>Loisir</libelle><texte>Kayak Polo</texte></contact></carnet>
